####COLOR DEFINITIONS FOR RGB OLED ####

COLOR_WHITE     = "white"
COLOR_BLACK     = "#000000"
COLOR_RED       = "#ff0000"
COLOR_YELLOW    = "#ffff00"
COLOR_BLUE      = "#000000"
COLOR_GREEN     = "#00ff00"
COLOR_BLUE      = "#0000ff"
COLOR_ORANGE     = "#FFA500"


COLOR_ERROR     = COLOR_ORANGE

COLOR_SELECTED = COLOR_YELLOW
COLOR_SELECTED_OUTLINE = "black"
